---
- name: Install modules
  become: yes
  community.general.npm:
    name: "{{ item.name }}"
    version: "{{ item.version|default('') }}"
    state: present
    global: yes
    unsafe_perm: yes
  with_items:
    - name: homebridge
      version: "{{ homebridge_version }}"
    - name: homebridge-config-ui-x
      version: "{{ homebridge_config_ui_version }}"

- name: Setup Homebridge service
  become: yes
  shell: hb-service install --user homebridge
  args:
    creates: /etc/systemd/system/homebridge.service

- name: Update the config file
  become: yes
  template:
    src: config.json.j2
    dest: "{{ homebridge_dir }}/config.json"
    owner: homebridge
    group: homebridge
  notify: Restart Homebridge

- name: Install plugins
  become: yes
  community.general.npm:
    name: "{{ item.name }}"
    version: "{{ item.version|default('') }}"
    state: present
    global: yes
    unsafe_perm: yes
  with_items: "{{ homebridge_plugins }}"
  notify: Restart Homebridge

- name: Start Homebridge
  become: yes
  systemd:
    name: homebridge
    state: started
    enabled: true