---
- name: Install modules
  community.general.npm:
    name: "{{ item.name }}"
    version: "{{ item.version|default('') }}"
    state: present
    global: yes
    unsafe_perm: yes
  with_items:
    - name: homebridge
      version: "{{ homebridge_version }}"
    - name: homebridge-config-ui-x
      version: "{{ homebridge_config_ui_version }}"
  notify: Restart Homebridge

- name: Setup Homebridge service
  shell: hb-service install --user homebridge
  args:
    creates: /etc/systemd/system/homebridge.service

- name: Set defaults
  template:
    src: homebridge.sh.j2
    dest: "/etc/default/homebridge"
    owner: homebridge
    group: homebridge
  notify: Restart Homebridge

- name: Update the config file
  template:
    src: config.json.j2
    dest: "{{ homebridge_dir }}/config.json"
    owner: homebridge
    group: homebridge
  notify: Restart Homebridge

- name: Install plugins
  community.general.npm:
    name: "{{ item.name }}"
    version: "{{ item.version|default('') }}"
    state: present
    global: yes
    unsafe_perm: yes
  with_items: "{{ homebridge_plugins }}"
  notify: Restart Homebridge

- name: Start Homebridge
  systemd:
    name: homebridge
    state: started
    enabled: true

- name: Ensure ports open on the firewall
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - { port: 8581, proto: "tcp" } # Web dashboard