---
- name: Create install directory
  ansible.builtin.file:
    path: "{{ homebridge_install_dir }}"
    state: directory
    mode: '0755'

- name: Copy the config file
  ansible.builtin.template:
    src: config.json.j2
    dest: "{{ homebridge_install_dir }}/config.json"
    mode: '0644'
  notify: Restart Homebridge

- name: Copy docker-compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ homebridge_install_dir }}/docker-compose.yml"
    mode: '0644'

- name: Ensure stack is running
  community.docker.docker_compose:
    project_name: Homebridge
    project_src: "{{ homebridge_install_dir }}"
    state: present
    pull: true

- name: Install plugins
  community.general.npm:
    name: "{{ item.name }}"
    version: "{{ item.version | default('') }}"
    state: present
    # global: true
    unsafe_perm: true
    path: "{{ homebridge_install_dir }}"
  with_items: "{{ homebridge_plugins }}"
  notify: Restart Homebridge

- name: Cleanup stale Docker images
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: false

- name: Ensure ports open on the firewall
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - { port: "{{ homebridge_port_http }}", proto: "tcp" } # HTTP dashboard
    - { port: 5353, proto: "udp" } # mDNS
    - { port: 5353, proto: "tcp" } # mDNS
    - { port: 51454, proto: "tcp" } # Bridge (See config.json)

- name: Ensure ports open on the firewall for plugins
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items: "{{ homebridge_plugin_ports }}"
