---
# - name: Fetch Node setup script
#   get_url:
#     url: https://deb.nodesource.com/setup_16.x
#     dest: /tmp/setup_node
#     mode: '0755'
#   register: node_setup_script

# - name: Execute Node setup script
#   become: yes
#   shell: /tmp/setup_node
#   when: node_setup_script.changed

- name: Install packages
  become: yes
  apt:
    state: present
    name:
      - gcc
      - g++
      - make
      - python3
      - net-tools

- name: Install ffmpeg
  become: yes
  apt:
    state: present
    name:
      - libavahi-compat-libdnssd-dev
      - ffmpeg