---
- name: Install Python
  become: true
  apt:
    update_cache: yes
    state: latest
    name:
    - python3
    - python3-pip

- name: Install Pip modules
  pip:
    name: docker
    version: 4.4.0
