---
- name: Ensure container is running
  docker_container:
    name: telegraf
    image: telegraf:latest
    state: started
    restart: no
    restart_policy: unless-stopped
    pull: yes
    volumes:
      - /opt/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro
    env:
      HOST_ETC: "{{ telegraf_host_etc }}"
      HOST_PROC: "{{ telegraf_host_proc }}"
      HOST_SYS: "{{ telegraf_host_sys }}"
      HOST_VAR: "{{ telegraf_host_var }}"
      HOST_RUN: "{{ telegraf_host_run }}"
      HOST_MOUNT_PREFIX: "{{ telegraf_host_mnt_prefix }}"