---
- name: Create install directory
  ansible.builtin.file:
    path: "{{ telegraf_install_dir }}"
    state: directory
    mode: '0755'

- name: Copy docker-compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ telegraf_install_dir }}/docker-compose.yml"
    mode: '0644'

- name: Copy telegraf.conf
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: "{{ telegraf_install_dir }}/telegraf.conf"
    mode: '0644'
  notify: Restart Telegraf

- name: Ensure stack is running
  community.docker.docker_compose:
    project_name: Telegraf
    project_src: "{{ telegraf_install_dir }}"
    state: present
    pull: true

- name: Cleanup stale Docker images
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: false
