---
- name: Create volume directory
  file:
    path: /opt/scrypted/volume
    state: directory
    mode: '0755'

- name: Ensure container is running
  docker_container:
    name: scrypted
    image: koush/scrypted:latest
    state: started
    restart: no
    restart_policy: unless-stopped
    pull: yes
    network_mode: host
    volumes:
      - /opt/scrypted/volume/:/server/volume

# - name: Install plugins

- name: Cleanup stale Docker images
  docker_prune:
    images: yes
    images_filters:
      dangling: false

- name: Ensure ports open on the firewall
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - { port: 10443, proto: "tcp" } # Web dashboard