---
- name: Create install directory
  file:
    path: "{{ plex_install_dir }}"
    state: directory
    mode: '0755'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ plex_database_dir }}"
    - "{{ plex_transcode_dir }}"

- name: Copy docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ plex_install_dir }}/docker-compose.yml"
    mode: '0644'

- name: Ensure stack is running
  docker_compose:
    project_name: Plex
    project_src: "{{ plex_install_dir }}"
    state: present
    pull: yes

- name: Cleanup stale Docker images
  docker_prune:
    images: yes
    images_filters:
      dangling: false

- name: Ensure port open on the firewall
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - { port: "{{ plex_port_http }}", proto: "tcp" } # HTTP traffic
    # - { port: 8920, proto: "tcp"} # HTTPS traffic
    # - { port: 1900, proto: "udp"} # Service auto-discovery
    # - { port: 7359, proto: "udp"} # Service auto-discovery