---
- name: Create install directory
  ansible.builtin.file:
    path: "{{ plex_install_dir }}"
    state: directory
    mode: '0755'

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ plex_database_dir }}"
    - "{{ plex_transcode_dir }}"

- name: Copy docker-compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ plex_install_dir }}/docker-compose.yml"
    mode: '0644'

- name: Ensure stack is running
  community.docker.docker_compose:
    project_name: Plex
    project_src: "{{ plex_install_dir }}"
    state: present
    pull: true

- name: Cleanup stale Docker images
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: false

- name: Ensure port open on the firewall
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - { port: "{{ plex_port_http }}", proto: "tcp" } # HTTP traffic
    # - { port: 8920, proto: "tcp"} # HTTPS traffic
    # - { port: 1900, proto: "udp"} # Service auto-discovery
    # - { port: 7359, proto: "udp"} # Service auto-discovery
