---
- name: Install packages
  become: true
  apt:
    update_cache: yes
    name: nfs-common
    state: present

- name: Mount NFS
  become: yes
  mount:
    src: "{{ plex_nas_host }}:{{ plex_nas_mount_path }}"
    path: "{{ plex_local_nas_mount_path }}"
    fstype: nfs
    opts: defaults
    dump: '0'
    passno: '0'
    state: mounted