---
- name: Install packages
  become: true
  ansible.builtin.apt:
    name: nfs-common
    state: present

- name: Mount NFS
  become: true
  ansible.posix.mount:
    src: "{{ plex_nas_host }}:{{ plex_nas_mount_path }}"
    path: "{{ plex_local_nas_mount_path }}"
    fstype: nfs
    opts: mountvers=4
    dump: '0'
    passno: '0'
    state: mounted
