---
- name: Create install directory
  ansible.builtin.file:
    path: "{{ homepage_install_dir }}"
    state: directory
    mode: '0755'

- name: Create config directory
  ansible.builtin.file:
    path: "{{ homepage_config_dir }}"
    state: directory
    mode: '0755'

- name: Copy config files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ homepage_config_dir }}/{{ item }}"
    mode: '0664'
  with_items:
    - docker.yaml
    - kubernetes.yaml
    - bookmarks.yaml
    - services.yaml
    - settings.yaml
    - widgets.yaml
  notify: Restart Homepage

- name: Copy docker-compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ homepage_install_dir }}/docker-compose.yml"
    mode: '0644'

- name: Ensure stack is running
  community.docker.docker_compose:
    project_name: Homepage
    project_src: "{{ homepage_install_dir }}"
    state: present
    pull: true

- name: Cleanup stale Docker images
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: false

- name: Ensure port open on the firewall
  community.general.ufw:
    rule: allow
    port: "{{ homepage_port_http }}"
    proto: tcp
