---
- name: Install packages
  become: true
  apt:
    name: nfs-common
    state: present

- name: Mount NFS
  become: yes
  mount:
    src: "{{ jellyfin_nas_host }}:{{ jellyfin_nas_mount_path }}"
    path: "{{ jellyfin_local_nas_mount_path }}"
    fstype: nfs
    opts: mountvers=4
    dump: '0'
    passno: '0'
    state: mounted