---
- name: Create install directory
  ansible.builtin.file:
    path: "{{ traefik_installation_dir }}"
    state: directory
    mode: '0755'

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ traefik_dir_letsencrypt }}"
    - "{{ traefik_dir_dynamic_config }}"

- name: Copy the static config file
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: "{{ traefik_installation_dir }}/traefik.yml"
    mode: '0644'
  notify: Restart Traefik

- name: Copy the dynamic config file
  ansible.builtin.template:
    src: services.yml.j2
    dest: "{{ traefik_dir_dynamic_config }}/services.yml"
    mode: '0644'

- name: Copy docker-compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ traefik_installation_dir }}/docker-compose.yml"
    mode: '0644'

- name: Ensure stack is running
  community.docker.docker_compose:
    project_name: Traefik
    project_src: "{{ traefik_installation_dir }}"
    state: present

- name: Cleanup stale Docker images
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: false

- name: Ensure port open on the firewall for HTTPS dashboard
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - "{{ traefik_port_api }}"
    - "{{ traefik_port_http }}"
    - "{{ traefik_port_https }}"
