---
- name: Create installation directory
  file:
    path: "{{ grafana_install_dir }}"
    state: directory
    mode: '0775'

- name: Create data directory
  file:
    path: "{{ grafana_data_dir }}"
    state: directory
    mode: '0775'

- name: Copy docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ grafana_install_dir }}/docker-compose.yml"
    mode: '0644'

- name: Ensure stack is running
  docker_compose:
    project_name: Grafana
    project_src: "{{ grafana_install_dir }}"
    state: present
    pull: yes

- name: Cleanup stale Docker images
  docker_prune:
    images: yes
    images_filters:
      dangling: false

- name: Ensure ports open on the firewall
  ufw:
    rule: allow
    port: "{{ grafana_port }}"
    proto: tcp