---
- name: Create installation directory
  ansible.builtin.file:
    path: "{{ grafana_install_dir }}"
    state: directory
    mode: '0775'

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0775'
  with_items:
    - "{{ grafana_data_dir }}"
    - "{{ grafana_provisioning_dir }}"
    - "{{ grafana_datasource_dir }}"
    - "{{ grafana_plugin_dir }}"
    - "{{ grafana_notifier_dir }}"
    - "{{ grafana_alerting_dir }}"
    - "{{ grafana_dashboard_dir }}"

- name: Copy datasource config
  ansible.builtin.template:
    src: datasource.yml.j2
    dest: "{{ grafana_datasource_dir }}/datasource.yml"
    mode: '0755'
  notify: Restart Grafana

- name: Copy docker-compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ grafana_install_dir }}/docker-compose.yml"
    mode: '0644'

- name: Ensure stack is running
  community.docker.docker_compose:
    project_name: Grafana
    project_src: "{{ grafana_install_dir }}"
    state: present
    pull: true

- name: Cleanup stale Docker images
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: false

- name: Ensure ports open on the firewall
  community.general.ufw:
    rule: allow
    port: "{{ grafana_port }}"
    proto: tcp
