pihole_web_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31333831663633383333636135313162373839636166383761663361373261306563323138316364
          3730303636623563616234663734643636636330336635630a623664383464393837626531633863
          61356364366433616134396533366463323536613764333136613733343231336239313434323466
          3430333938353131660a626363396435383965386534303365643138396636366438306466353536
          62643235626235336437623631343338636637633464623634643836666631643264

pihole_timezone: "America/Denver"
pihole_dnsmasq: "all"

pihole_adlists:
  - address: "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
    comment: "Migrated from /etc/pihole/adlists.list"
  - address: "https://blocklistproject.github.io/Lists/abuse.txt"
    comment: "Block List Project (Abuse)"
  - address: "https://blocklistproject.github.io/Lists/ads.txt"
    comment: "Block List Project (Ads)"
  - address: "https://blocklistproject.github.io/Lists/malware.txt"
    comment: "Block List Project (Malware)"
  - address: "https://blocklistproject.github.io/Lists/phishing.txt"
    comment: "Block List Project (Phishing)"
  - address: "https://blocklistproject.github.io/Lists/porn.txt"
    comment: "Block List Project (Porn)"
  - address: "https://blocklistproject.github.io/Lists/ransomware.txt"
    comment: "Block List Project (Ransomware)"
  - address: "https://blocklistproject.github.io/Lists/redirect.txt"
    comment: "Block List Project (Redirect)"
  - address: "https://blocklistproject.github.io/Lists/scam.txt"
    comment: "Block List Project (Scam)"
  - address: "https://blocklistproject.github.io/Lists/tracking.txt"
    comment: "Block List Project (Tracking)"
  - address: "https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt"
    comment: "Developer Dan (Ads & Tracking)"
  - address: "https://www.github.developerdan.com/hosts/lists/dating-services-extended.txt"
    comment: "Developer Dan (Dating Services)"
  - address: "https://adaway.org/hosts.txt"
  - address: "https://v.firebog.net/hosts/AdguardDNS.txt"
  - address: "https://v.firebog.net/hosts/Admiral.txt"
  - address: "https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt"
  - address: "https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt"
  - address: "https://v.firebog.net/hosts/Easylist.txt"
  - address: "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext"
  - address: "https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts"
  - address: "https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts"

pihole_domainlist:
  - domain: "(\\.|^)plausible\\.io$"
    type: 2
    comment: "Allow plausible.io"
  - domain: "fonts.gstatic.com"
    type: 0
  - domain: "t.co"
    type: 0