---
- name: Create install directory
  ansible.builtin.file:
    path: "{{ influxdb_install_dir }}"
    state: directory
    mode: '0755'

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ influxdb_data_dir }}"
    - "{{ influxdb_config_dir }}"

- name: Copy docker-compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ influxdb_install_dir }}/docker-compose.yml"
    mode: '0644'

- name: Ensure stack is running
  community.docker.docker_compose:
    project_name: InfluxDB
    project_src: "{{ influxdb_install_dir }}"
    state: present
    pull: true

- name: Cleanup stale Docker images
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: false

- name: Ensure ports open on the firewall
  community.general.ufw:
    rule: allow
    port: "{{ influxdb_port }}"
    proto: "tcp"
