---
- name: Create install directory
  file:
    path: "{{ influxdb_install_dir }}"
    state: directory
    mode: '0755'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ influxdb_data_dir }}"
    - "{{ influxdb_config_dir }}"

- name: Copy docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ influxdb_install_dir }}/docker-compose.yml"
    mode: '0644'

- name: Ensure stack is running
  docker_compose:
    project_name: InfluxDB
    project_src: "{{ influxdb_install_dir }}"
    state: present
    pull: yes

- name: Cleanup stale Docker images
  docker_prune:
    images: yes
    images_filters:
      dangling: false

- name: Ensure ports open on the firewall
  ufw:
    rule: allow
    port: "{{ influxdb_port }}"
    proto: "tcp"