---
- name: Create install directory
  file:
    path: "{{ portainer_install_dir }}"
    state: directory
    mode: '0755'

- name: Create data directory
  file:
    path: "{{ portainer_data_dir }}"
    state: directory
    mode: '0755'

- name: Copy docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ portainer_install_dir }}/docker-compose.yml"
    mode: '0644'

- name: Ensure stack is running
  docker_compose:
    project_name: Portainer
    project_src: "{{ portainer_install_dir }}"
    state: present
    pull: yes

- name: Cleanup stale Docker images
  docker_prune:
    images: yes
    images_filters:
      dangling: false

- name: Ensure ports open on the firewall
  ufw:
    rule: allow
    port: "{{ portainer_port_https }}"
    proto: tcp