---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ traefik_dir_letsencrypt }}"
    - "{{ traefik_dir_services }}"

- name: Setup the services file
  template:
    src: config.yml.j2
    dest: "{{ traefik_dir_services }}/config.yml"
    mode: '0644'
# TODO: restart container if this changed

- name: Ensure ports open on the firewall
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - { port: "{{ traefik_port_https }}", proto: "tcp" }