---
- name: Create installation directory
  file:
    path: "{{ uptime_kuma_install_dir }}"
    state: directory
    mode: '0755'

- name: Create data directory
  file:
    path: "{{ uptime_kuma_data_dir }}"
    state: directory
    mode: '0755'

- name: Copy docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ uptime_kuma_install_dir }}/docker-compose.yml"
    mode: '0644'

- name: Ensure stack is running
  docker_compose:
    project_name: Uptime Kuma
    project_src: "{{ uptime_kuma_install_dir }}"
    state: present

- name: Cleanup stale Docker images
  docker_prune:
    images: yes
    images_filters:
      dangling: false

- name: Ensure ports open on the firewall
  ufw:
    rule: allow
    port: "{{ uptime_kuma_port }}"
    proto: tcp