---
- name: Create install directory
  ansible.builtin.file:
    path: "{{ prometheus_install_dir }}"
    state: directory
    mode: "0744"

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
  with_items:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_data_dir }}"

- name: Copy config files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ prometheus_config_dir }}/{{ item }}"
    mode: "0666"
  with_items:
    - prometheus.yml
    - web-config.yml
  notify: Restart Prometheus

- name: Copy docker-compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ prometheus_install_dir }}/docker-compose.yml"
    mode: "0644"

- name: Ensure stack is running
  community.docker.docker_compose:
    project_name: Prometheus
    project_src: "{{ prometheus_install_dir }}"
    state: present
    pull: true

- name: Cleanup stale Docker images
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: false

- name: Ensure ports open on the firewall
  community.general.ufw:
    rule: allow
    port: "{{ prometheus_port }}"
    proto: tcp
