---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Ensure /etc/hosts contains an entry with the hostname
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127.0.0.1 localhost'
    line: '127.0.0.1 localhost {{ inventory_hostname }}'

- name: Get host architecture
  ansible.builtin.command: uname -m
  register: guest_base_uname_output
  changed_when: false

- name: Save host_arch
  ansible.builtin.set_fact:
    guest_base_host_arch: "{{ guest_base_uname_output.stdout }}"

- name: Ensure packages are up-to-date
  ansible.builtin.apt:
    # upgrade: true
    update_cache: true
    cache_valid_time: 86400 # One day

- name: Ensure ufw is installed
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Ensure default deny on firewall
  community.general.ufw:
    default: deny

- name: Ensure SSH available through firewall
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Ensure firewall enabled and running
  community.general.ufw:
    state: enabled

- name: Ensure fail2ban is installed
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Ensure fail2ban is enabled and running
  ansible.builtin.systemd:
    name: fail2ban
    state: started

- name: Disable password auth for SSH
  ansible.builtin.template:
    src: disablePasswordAuth.j2
    dest: /etc/ssh/sshd_config.d/disablePasswordAuth.conf
  notify: Restart sshd

- name: Check if the partition can be expanded
  ansible.builtin.command: "growpart {{ filesystem_device }} {{ filesystem_device_number }} --dry-run"
  changed_when: false
  failed_when: false
  register: guest_base_growpart_check

- name: Expand the partition to fill available space
  ansible.builtin.command: "growpart {{ filesystem_device }} {{ filesystem_device_number }}"
  changed_when: true
  when: guest_base_growpart_check.rc == 0

- name: Extend the filesystem
  community.general.filesystem:
    fstype: "{{ filesystem_type }}"
    dev: "{{ filesystem_device }}{{ filesystem_device_number }}"
    resizefs: true
  when: guest_base_growpart_check.rc == 0
