---
- hosts: guests
  become: true
  roles:
    - guest-base

- hosts: piholes
  become: true
  serial: 1 # Prevent a total loss of DNS on the network
  vars:
    pip_package: python3-pip
  vars_files:
    - vars/pihole.yml
  roles:
    - geerlingguy.pip
    - geerlingguy.docker_arm
    - docker-monitoring
    - pihole

- hosts: homelab-prx
  become: true
  vars:
    pip_package: python3-pip
    docker_install_compose: true
  vars_files:
    - vars/cloudflare-ddns.yml
    - vars/traefik.yml
  roles:
    - geerlingguy.pip
    - geerlingguy.docker_arm
    - docker-monitoring
    - cloudflare-ddns
    - traefik

- hosts: homelab-mon
  become: true
  vars:
    pip_package: python3-pip
    docker_install_compose: true
    pip_install_packages:
      - name: docker
      - name: docker-compose
  #   - nodejs_version: "16.x"
  vars_files:
    # - vars/homebridge.yml
    # - vars/pihole.yml
    # - vars/scrypted.yml
    - vars/influxdb.yml
    - vars/grafana.yml
    - vars/portainer.yml
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - docker-monitoring
    - influxdb
    - grafana
    - portainer
    - uptime-kuma

# - hosts: coruscant
#   become: true
#   roles:
#     - geerlingguy.docker
#     - geerlingguy.pip
#     - homebridge
#     - plex
#     - portainer
  # vars:
  #   pip_install_packages:
  #     - name: docker
  # vars_files:
  #   - vars/homebridge.yml
  #   - vars/plex.yml
