---
# Run base roles against all ESXi hosts
- name: Base configuration for all ESXi hosts
  hosts: esxi
  gather_facts: false
  roles:
    - esx_base

# Run base roles against all guests, including Docker setup
- name: Base configuration for all guests
  hosts: guests
  become: true
  roles:
    - guest_base
    - geerlingguy.pip
    - geerlingguy.docker
    - telegraf
    - docker_monitoring

# Setup Pi-holes
- name: Configure Pi-holes
  hosts: piholes
  become: true
  serial: 1 # Prevent a total loss of DNS on the network
  roles:
    - pihole

# Traefik
- name: Install Traefik
  hosts: plausible.vojak.cloud,plex.vojak.cloud,routing.vojak.cloud,homebridge.vojak.cloud,monitoring.vojak.cloud
  become: true
  roles:
    - traefik

# Plausible
- name: Configure Plausible
  hosts: plausible.vojak.cloud
  become: true
  roles:
    - plausible

# Plex
- name: Configure Plex
  hosts: plex.vojak.cloud
  become: true
  roles:
    - plex

# Minecraft
- name: Configure Minecraft
  hosts: minecraft.vojak.cloud
  become: true
  roles:
    - minecraft

# Routing applications and dashboard
- name: Configuring routing services
  hosts: routing.vojak.cloud
  become: true
  roles:
    - cloudflare_ddns
    - homepage

# Homebridge and smart home
- name: Configure Homebridge
  hosts: homebridge.vojak.cloud
  become: true
  roles:
    - geerlingguy.nodejs
    - homebridge
    - scrypted

# Prometheus, Grafana, InfluxDB, and other monitoring tools
- name: Configure monitoring services
  hosts: monitoring.vojak.cloud
  become: true
  roles:
    - influxdb
    - grafana
    - portainer
    - uptime_kuma
    - prometheus
    - pihole_influxdb_monitor
    - speedtest
    # - un-poller
