---
- hosts: coruscant
  become: true
  roles:
    - geerlingguy.docker
    - geerlingguy.pip
    - homebridge
    - plex
    - portainer
  vars:
    pip_install_packages:
      - name: docker
  vars_files:
    - vars/homebridge.yml
    - vars/plex.yml
