---
# Run base role against all guests
- hosts: guests
  become: true
  roles:
    - guest-base

# Install Docker on ARM guests
- hosts: guests:&arm64
  become: true
  vars:
    pip_package: python3-pip
    docker_install_compose: true
  roles:
    - geerlingguy.pip
    - geerlingguy.docker_arm

# Install Docker on x86 guests
- hosts: guests:&amd64
  become: true
  vars:
    pip_package: python3-pip
    docker_install_compose: true
    pip_install_packages:
      - name: docker
      - name: docker-compose
  roles:
    - geerlingguy.pip
    - geerlingguy.docker

# Install Docker-based monitoring on all guests
- hosts: guests
  become: true
  vars_files:
    - roles/influxdb/defaults/main.yml
    - vars/influxdb.yml
  roles:
    - telegraf
    - docker-monitoring

# Setup Pi-holes
- hosts: piholes
  become: true
  serial: 1 # Prevent a total loss of DNS on the network
  vars_files:
    - vars/pihole.yml
  roles:
    - pihole

# Install homelab proxy & routing tools
- hosts: homelab-prx
  become: true
  vars_files:
    - vars/cloudflare-ddns.yml
    - vars/traefik.yml
    - vars/heimdall.yml
  roles:
    - cloudflare-ddns
    - traefik
    - heimdall

# Installing homelab monitoring tools
- hosts: homelab-mon
  become: true
  vars_files:
    - vars/influxdb.yml
    - vars/grafana.yml
    - vars/portainer.yml
  roles:
    - influxdb
    - grafana
    - portainer
    - uptime-kuma

# - hosts: homelab-app-01
#   become: true
#   vars_files:
#     - vars/heimdall.yml
#   roles:
#     - heimdall

# - hosts: coruscant
#   become: true
#   roles:
#     - geerlingguy.docker
#     - geerlingguy.pip
#     - homebridge
#     - plex
#     - portainer
  # vars:
  #   pip_install_packages:
  #     - name: docker
  # vars_files:
  #   - vars/homebridge.yml
  #   - vars/plex.yml
