---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Get host architecture
  shell: uname -m
  register: uname_output
  changed_when: false

- name: Save host_arch
  set_fact: host_arch="{{ uname_output.stdout }}"

- name: Ensure packages are up-to-date
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # One day

- name: Ensure ufw is installed
  apt:
    name: ufw
    state: latest

- name: Ensure default deny on firewall
  ufw:
    default: deny

- name: Ensure SSH available through firewall
  ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Ensure firewall enabled and running
  ufw:
    state: enabled