traefik_version: latest
traefik_dashboard_domain: traefik.example.com
traefik_username: admin
traefik_password: P@$$w0rd
traefik_email_address: admin@example.com
traefik_log_level: DEBUG
traefik_port_http: 80
traefik_port_https: 443
traefik_installation_dir: /opt/traefik
traefik_dir_letsencrypt: "{{ traefik_installation_dir }}/letsencrypt"
traefik_dir_services: "{{ traefik_installation_dir }}/services"