speedtest_version: latest
speedtest_install_dir: /opt/speedtest
speedtest_influxdb_scheme: http
speedtest_influxdb_host: localhost
speedtest_influxdb_port: 8086
speedtest_influxdb_admin_token: asdfghjkl
speedtest_influxdb_org: my_test_org
speedtest_influxdb_database: SpeedtestStats # The bucket
speedtest_interval: 3600 # Seconds
speedtest_host: server04
speedtest_server: 41817