---
- name: Create install directory
  file:
    path: "{{ cloudflare_ddns_install_dir }}"
    state: directory
    mode: '0755'

- name: Copy docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ cloudflare_ddns_install_dir }}/docker-compose.yml"
    mode: '0644'

- name: Ensure stack is running
  docker_compose:
    project_name: Cloudflare DDNS
    project_src: "{{ cloudflare_ddns_install_dir }}"
    state: present

- name: Cleanup stale Docker images
  docker_prune:
    images: yes
    images_filters:
      dangling: false